"""empty message

Revision ID: 0e0871d21e17
Revises: 
Create Date: 2025-01-07 15:27:24.693713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e0871d21e17'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subreddits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=21), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='readdit_clone_schema'
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('profile_image', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username'),
    schema='readdit_clone_schema'
    )
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('body', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('subreddit_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['subreddit_id'], ['readdit_clone_schema.subreddits.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['readdit_clone_schema.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='readdit_clone_schema'
    )
    op.create_table('users_subreddits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subreddit_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['subreddit_id'], ['readdit_clone_schema.subreddits.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['readdit_clone_schema.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='readdit_clone_schema'
    )
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reply_to_id', sa.Integer(), nullable=True),
    sa.Column('body', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('subreddit_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['readdit_clone_schema.posts.id'], ),
    sa.ForeignKeyConstraint(['subreddit_id'], ['readdit_clone_schema.subreddits.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['readdit_clone_schema.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='readdit_clone_schema'
    )
    op.create_table('images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['readdit_clone_schema.posts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='readdit_clone_schema'
    )
    op.create_table('post_likes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('like_status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['readdit_clone_schema.posts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['readdit_clone_schema.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='readdit_clone_schema'
    )
    op.create_table('comment_likes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('like_status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['readdit_clone_schema.comments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['readdit_clone_schema.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='readdit_clone_schema'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comment_likes', schema='readdit_clone_schema')
    op.drop_table('post_likes', schema='readdit_clone_schema')
    op.drop_table('images', schema='readdit_clone_schema')
    op.drop_table('comments', schema='readdit_clone_schema')
    op.drop_table('users_subreddits', schema='readdit_clone_schema')
    op.drop_table('posts', schema='readdit_clone_schema')
    op.drop_table('users', schema='readdit_clone_schema')
    op.drop_table('subreddits', schema='readdit_clone_schema')
    # ### end Alembic commands ###
