"""empty message

Revision ID: bfb5be286d61
Revises: 44631e906524
Create Date: 2025-07-04 14:16:06.654857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfb5be286d61'
down_revision = '44631e906524'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment_likes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('post_id', sa.Integer(), nullable=False))

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.alter_column('is_reply',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.alter_column('deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('is_reply',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    with op.batch_alter_table('comment_likes', schema=None) as batch_op:
        batch_op.drop_column('post_id')

    # ### end Alembic commands ###
