name: Main Branch Pull Request Protection
run-name: Main branch PR protection
on:
  pull_request:
    branches:
      - main

jobs:
  check-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR source
        run: |
          if [[ ${GITHUB_HEAD_REF} != staging ]];
            then
              echo "Error: Pull request to the 'main' branch must come from 'staging' branch"
              exit 1
            fi
